HW1 project containerization
otusteamedu/PHP_2024 pull request #133
Opened 2024-02-22 20:11 UTC by a7000q

2024-02-23 08:45 UTC, dshemin requested changes

2024-02-23 08:45 UTC, dshemin commented on docker-compose.yml
> +      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
У нас есть переменные окружения - это хорошо. Но если кто-то будет запускать проект, ему прийдётся обойти все файлы, чтобы понять какие переменные окружения надо выставить и что в них надо указать.

Для этого принято добавлять .env.example, со всеми переменными окружения и примерами значений.

2024-02-23 10:14 UTC, a7000q commented on docker-compose.yml
> +      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
Добавил .env.example

2024-02-26 14:11 UTC, dshemin approved these changes

2024-02-26 14:13 UTC, merged