HW14 search in otus-shop index
otusteamedu/PHP_2024 pull request #278
Opened 2024-03-19 05:10 UTC by a7000q

2024-03-19 07:00 UTC, dshemin requested changes

2024-03-19 07:38 UTC, a7000q commented on src/Commands/Elastic/AbstractOtusShopCommand.php
> +    public function init(): void
не совсем понял замечание. инъектить явно значит в конструкторе?

2024-03-22 03:18 UTC, dshemin requested changes

2024-03-22 03:18 UTC, dshemin commented on src/Commands/Elastic/AbstractOtusShopCommand.php
> +        $this->otusShopRepository = new OtusShopRepository($this->elasticClient);
Создайте объект данного класса вне данного класса и инъектите сюда через конструктор.

2024-03-22 03:18 UTC, dshemin commented on src/Commands/AbstractCommand.php
> +        $this->argv = array_slice($_SERVER['argv'], 2);
Не создавайте классы внутри других классов. Передавайте через конструктор. Таких мест несколько, пробегите весь код и поправьте везде.

2024-03-25 03:27 UTC, dshemin requested changes

2024-03-25 03:27 UTC, dshemin commented on src/Commands/Elastic/OtusShopImportCommand.php
> +        $otusShopRepository = new OtusShopRepository($this->elasticClient);
Смотрите. Если вы видите что где-то в коде класса (кроме App), есть `new ...` то надо рефакторить и выносить класс в конструктор.

2024-03-25 03:27 UTC, dshemin commented on src/Commands/Elastic/OtusShopRemoveIndexCommand.php
> +        $otusShopRepository = new OtusShopRepository($this->elasticClient);
Должен быть передан в конструктор как зависимость.

2024-03-25 03:27 UTC, dshemin commented on src/Commands/Elastic/OtusShopSearchCommand.php
> +        $otusShopRepository = new OtusShopRepository($this->elasticClient);
Передайте как зависимость.

2024-03-29 06:36 UTC, dshemin requested changes

2024-03-29 06:36 UTC, dshemin commented on src/Commands/AbstractCommand.php
> +    public function __construct(ConfigManager $configManager, Container $container)
Зависимость от контейнера - антипаттерн. Усложняет понимание кода и использование. Просто объявите зависимость от КОНКРЕТНЫХ интерфейсов.

2024-03-31 15:32 UTC, dshemin requested changes

2024-03-31 15:32 UTC, dshemin commented on src/Commands/AbstractCommand.php
> +    public function __construct(ConfigManager $configManager, ContainerInterface $container)
Вот тут осталось использование контейнера.

2024-03-31 15:32 UTC, dshemin commented on src/Commands/Elastic/OtusShopImportCommand.php
> +        $otusShopRepository = $this->container->get(OtusShopRepository::class);
Вот тут осталось использование контейнера.

2024-03-31 15:32 UTC, dshemin commented on src/Commands/Elastic/OtusShopRemoveIndexCommand.php
> +        $otusShopRepository = $this->container->get(OtusShopRepository::class);
Вот тут осталось использование контейнера.

2024-03-31 15:32 UTC, dshemin commented on src/Commands/Elastic/OtusShopSearchCommand.php
> +        $otusShopRepository = $this->container->get(OtusShopRepository::class);
Вот тут осталось использование контейнера.

2024-03-31 15:32 UTC, dshemin commented on src/Commands/EventSystem/AddEventCommand.php
> +        $repository = $this->container->get(EventRepositoryInterface::class);
Вот тут осталось использование контейнера.

2024-03-31 15:32 UTC, dshemin commented on src/Commands/EventSystem/RemoveAllEventCommand.php
> +        $repository = $this->container->get(EventRepositoryInterface::class);
Вот тут осталось использование контейнера.

2024-03-31 15:32 UTC, dshemin commented on src/Commands/EventSystem/SearchEventCommand.php
> +        $repository = $this->container->get(EventRepositoryInterface::class);
Вот тут осталось использование контейнера.

2024-03-31 16:19 UTC, dshemin approved these changes

2024-04-03 06:29 UTC, merged